#!/usr/bin/env python3
##
## EPITECH PROJECT, 2023
## 102 architect
## File description:
## 103 cypher
##
import sys
import math

def print_h():
    print("USAGE\n    ./103cipher message key flag\n\nDESCRIPTION\n    message     a message, made of ASCII characters\n    key         the encryption key, made of ASCII characters\n    flag        0 for the message to be encrypted, 1 to be decrypted")
    return 0

def print_matrice(matrice):
    print("{:<7.2f}".format(matrice[0][0]),"{:<7.2f}".format(matrice[0][1]),"{:.2f}".format(matrice[0][2]))
    print("{:<7.2f}".format(matrice[1][0]),"{:<7.2f}".format(matrice[1][1]),"{:.2f}".format(matrice[1][2]))
    print("{:<7.2f}".format(matrice[2][0]),"{:<7.2f}".format(matrice[2][1]),"{:.2f}".format(matrice[2][2]))


def main(argv):
    if (argv[0] == "-h"):
        return print_h()

if __name__ == "__main__":
    try:
        main(sys.argv[1:])
    except:
        sys.exit(84)
    sys.exit(0)